import { Budget, Confidence, DataQuality, FocusSession, Projection, UsageSample } from './domain';

export const median = (values: number[]) => { const s = values.filter(Number.isFinite).sort((a,b) => a-b); if (!s.length) return 0; const m = Math.floor(s.length / 2); return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };
export function samplesIn(samples: UsageSample[], from: Date, to: Date) { return samples.filter(s => { const t = new Date(s.observedAt).getTime(); return t >= from.getTime() && t < to.getTime(); }); }
export function used(samples: UsageSample[], from: Date, to: Date) { const rows = samplesIn(samples, from, to); return rows.reduce((n, s) => n + s.credits, 0); }
export function period(kind: Budget['kind'], now = new Date()): [Date, Date] { const start = new Date(now); const end = new Date(now); if (kind === 'daily') { start.setHours(0,0,0,0); end.setDate(end.getDate()+1); end.setHours(0,0,0,0); } else if (kind === 'weekly') { const d=(now.getDay()+6)%7; start.setDate(now.getDate()-d); start.setHours(0,0,0,0); end.setTime(start.getTime()); end.setDate(end.getDate()+7); } else { start.setDate(1); start.setHours(0,0,0,0); end.setMonth(end.getMonth()+1,1); end.setHours(0,0,0,0); } return [start,end]; }
export function rate(samples: UsageSample[], now = new Date(), minutes = 30) { const from = new Date(now.getTime() - minutes * 60_000); return used(samples, from, now) / (minutes / 60); }
export function baseline(samples: UsageSample[], now = new Date()): number { const rates: number[] = []; for (let day=1; day<=28; day++) { const e = new Date(now.getTime() - day*86400000); const a = new Date(e); a.setMinutes(a.getMinutes()-30); const value = used(samples,a,e)/(0.5); if (value > 0) rates.push(value); } return median(rates); }
export function confidence(quality: DataQuality, sampleCount: number, observedAt?: string): Confidence { const age = observedAt ? Date.now()-new Date(observedAt).getTime() : Infinity; if (quality === 'exact' && age < 3600000 && sampleCount >= 8) return 'high'; if (quality !== 'estimated' && age < 36*3600000 && sampleCount >= 3) return 'medium'; return 'low'; }
export function forecast(budget: Budget, perHour: number, quality: DataQuality, samples: UsageSample[]): Projection { const hours = Math.max(0,(budget.periodEnd.getTime()-Date.now())/3600000); const remaining = Math.max(0,budget.amount-budget.consumed); return { budget, ratePerHour: perHour, projectedUsage: budget.consumed + perHour*hours, exhaustionAt: perHour>0 && remaining>0 ? new Date(Date.now()+remaining/perHour*3600000) : undefined, confidence: confidence(quality,samples.length,samples.at(-1)?.observedAt) }; }
export function state(ratio: number, absolute: number, risk: boolean) { if (risk && ratio >= 4 && absolute >= 10) return 'Critical'; if (ratio >= 2.5 && absolute >= 10) return 'Surge'; if (ratio >= 1.75 && absolute >= 6) return 'Elevated'; if (ratio >= 1.25) return 'Active'; return ratio < .8 ? 'Calm' : 'Normal'; }
export function sessionConsumed(session: FocusSession, samples: UsageSample[]) { return samples.filter(s => new Date(s.observedAt) >= new Date(session.startedAt)).reduce((n,s)=>n+s.credits,0); }
