import * as vscode from 'vscode';
import { DashboardModel } from './domain';
export class Dashboard {
  private panel?: vscode.WebviewPanel;
  constructor(private readonly extensionUri:vscode.Uri, private readonly getModel:()=>DashboardModel, private readonly onMessage:(x:unknown)=>void) {}
  open() { if (this.panel) { this.panel.reveal(); this.render(); return; } this.panel=vscode.window.createWebviewPanel('copilotPulse.dashboard','Copilot Pulse',vscode.ViewColumn.One,{enableScripts:true,retainContextWhenHidden:true,localResourceRoots:[this.extensionUri]}); this.panel.onDidDispose(()=>this.panel=undefined); this.panel.webview.onDidReceiveMessage(x=>this.onMessage(x)); this.render(); }
  render() { if (!this.panel) return; const model=this.getModel(); this.panel.webview.html=html(model); }
}
function html(m:DashboardModel) { const esc=(v:unknown)=>String(v ?? '').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]!)); const budget=m.budgets.map(b=>`<article class="ring ${m.quality}"><strong>${Math.round(b.amount ? b.consumed/b.amount*100 : 0)}%</strong><span>${b.kind.replace('billingCycle','cycle')}</span><small>${b.consumed.toFixed(1)} / ${b.amount}</small></article>`).join(''); const projections=m.projections.map(p=>`<li>${esc(p.budget.kind)}: <b>${p.projectedUsage.toFixed(0)} / ${p.budget.amount}</b> · ${esc(p.confidence)} confidence${p.exhaustionAt ? ` · runs out ${esc(p.exhaustionAt.toLocaleString())}`:''}</li>`).join(''); const trail=m.trail.slice(-24).map(x=>Math.min(8,Math.round(x.credits))).map(x=>'▁▂▃▄▅▆▇█'[x] ?? '▁').join(''); const session=m.session ? `<section><h2>Focus session</h2><p>${esc(m.session.name)} · target ${m.session.target} credits · ends ${esc(m.session.endsAt ? new Date(m.session.endsAt).toLocaleTimeString():'when you end it')}</p><button data-cmd="endSession">End session</button></section>` : '<button data-cmd="startSession">Start Focus Session</button>';
return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-pulse';"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:var(--vscode-font-family);color:var(--vscode-foreground);max-width:900px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center}.quality{border-style:dotted}.delayed{border-style:dashed}.exact{border-style:solid}.rings{display:flex;gap:16px;flex-wrap:wrap}.ring{border:6px solid var(--vscode-button-background);border-radius:50%;width:150px;height:150px;display:grid;place-content:center;text-align:center}.ring strong{font-size:2.2rem}.trail{font-size:2rem;letter-spacing:3px;color:var(--vscode-charts-blue)}section{border-top:1px solid var(--vscode-widget-border);margin-top:24px;padding-top:12px}button{background:var(--vscode-button-background);color:var(--vscode-button-foreground);border:0;padding:8px 12px;margin-right:8px}small{opacity:.8}</style></head><body><div class="top"><div><h1>Copilot Pulse · ${esc(m.weather)}</h1><p>${esc(m.quality)} · ${esc(m.freshness.explanation)} · ${m.freshness.observedAt ? esc(new Date(m.freshness.observedAt).toLocaleString()):'no observation'}</p></div><button data-cmd="refresh">Refresh</button></div><div class="rings" aria-label="Usage budgets">${budget}</div><section><h2>Current velocity</h2><p><b>${m.ratePerHour.toFixed(1)} credits/hour</b> · baseline ${m.baselineRate.toFixed(1)} · ${m.ratio.toFixed(1)}×</p><p class="trail" aria-label="Recent usage trail">${trail || 'No usage trail yet'}</p></section><section><h2>Forecast & runway</h2><ul>${projections}</ul></section>${session}<section><h2>Data and privacy</h2><p>Local-only history. No prompts, responses, or source code are collected.</p><button data-cmd="snapshot">Enter snapshot</button><button data-cmd="import">Import report</button><button data-cmd="economy">Economy Mode</button></section><script nonce="pulse">const v=acquireVsCodeApi();document.querySelectorAll('[data-cmd]').forEach(b=>b.addEventListener('click',()=>v.postMessage({command:b.dataset.cmd})));</script></body></html>`; }
