import * as vscode from 'vscode';
import { Alert, DashboardModel, DataQuality, FocusSession, UsageSample } from './domain';
import { baseline, forecast, period, rate, sessionConsumed, state, used } from './analytics';
import { Dashboard } from './dashboard';
import { parseReport } from './providers';
import { Store } from './storage';

let refreshUI: () => void = () => {};
export function activate(context:vscode.ExtensionContext) {
 const store=new Store(context); const cfg=()=>vscode.workspace.getConfiguration('copilotPulse');
 const model=():DashboardModel=> { const samples=store.samples().sort((a,b)=>a.observedAt.localeCompare(b.observedAt)); const quality:DataQuality=samples.at(-1)?.quality ?? 'estimated'; const now=new Date(); const budgets=['daily','weekly','billingCycle'] as const; const bs=budgets.map(kind=>{const [a,b]=period(kind,now); return {kind,amount:cfg().get<number>(`budgets.${kind}`,kind==='daily'?80:kind==='weekly'?400:1500),consumed:used(samples,a,b),periodStart:a,periodEnd:b};}); const current=rate(samples,now,cfg().get('spike.windowMinutes',30)); const base=baseline(samples,now); const ratio=current/Math.max(base,2); const projections=bs.map(b=>forecast(b,current,quality,samples)); const stale=!samples.length || Date.now()-new Date(samples.at(-1)?.observedAt ?? 0).getTime()>(quality==='delayed'?36:quality==='imported'?48:24)*3600000; const risky=projections.some(p=>p.projectedUsage>p.budget.amount); const weather=stale?'Unknown':state(ratio,current*(cfg().get('spike.windowMinutes',30)/60),risky); return {quality,freshness:{observedAt:samples.at(-1)?.observedAt,stale,explanation:stale?'Usage data is stale; forecasting is downgraded.':`${quality} local data`},now:now.toISOString(),budgets:bs,ratePerHour:current,baselineRate:base,ratio,weather,projections,trail:samples,session:store.session(),alerts:alerts(store,bs,projections,ratio,current,stale)}; };
 const dashboard=new Dashboard(context.extensionUri,model,message=>{if(!message || typeof message!=='object')return; const cmd=(message as {command?:string}).command; const map:Record<string,string>={refresh:'copilotPulse.refresh',startSession:'copilotPulse.startSession',endSession:'copilotPulse.endSession',snapshot:'copilotPulse.enterSnapshot',import:'copilotPulse.importReport',economy:'copilotPulse.enableEconomy'}; if(cmd && map[cmd]) vscode.commands.executeCommand(map[cmd]);});
 const status=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right,100); status.command='copilotPulse.openDashboard'; context.subscriptions.push(status); refreshUI=()=>{const m=model(); if(!cfg().get('enabled',true)){status.hide();return;} const p=m.projections.find(x=>x.budget.kind==='daily'); const mode=cfg().get<string>('statusBar.mode','adaptive'); const runway=p?.exhaustionAt?`${Math.max(0,Math.round((p.exhaustionAt.getTime()-Date.now())/3600000))}h runway`:''; status.text=m.freshness.stale?'$(circle-slash) Copilot · Estimate stale':mode==='budget'?`$(pulse) Copilot · ${p?.budget.consumed.toFixed(0)} / ${p?.budget.amount}`:mode==='burnRate'?`$(pulse) Copilot · ${m.weather} ${m.ratio.toFixed(1)}×`:m.weather==='Critical'?`$(flame) Copilot · ${runway}`:`$(pulse) Copilot · ${m.weather}${runway?` · ${runway}`:''}`; status.tooltip=`Copilot Pulse: ${m.quality}, ${m.freshness.explanation}`; status.show(); dashboard.render(); notify(m,store);};
 const command=(id:string,fn:()=>unknown)=>context.subscriptions.push(vscode.commands.registerCommand(id,fn));
 command('copilotPulse.openDashboard',()=>dashboard.open());
 command('copilotPulse.enterSnapshot',async()=>{const consumed=await vscode.window.showInputBox({prompt:'Current credits consumed this billing cycle',validateInput:v=>Number(v)>=0?'': 'Enter a non-negative number'}); if(consumed===undefined)return; const allowance=await vscode.window.showInputBox({prompt:'Official allowance (optional)',validateInput:v=>!v||Number(v)>=0?'':'Enter a non-negative number'}); const previous=store.samples().filter(s=>s.sourceId==='manual').at(-1); const delta=Math.max(0,Number(consumed)-(previous?.cumulativeCredits ?? 0)); await store.add([{id:`manual-${Date.now()}`,observedAt:new Date().toISOString(),credits:delta,cumulativeCredits:Number(consumed),quality:'estimated',sourceId:'manual',note:allowance?`Allowance: ${allowance}`:undefined}]); refreshUI();});
 command('copilotPulse.importReport',async()=>{const picks=await vscode.window.showOpenDialog({canSelectMany:false,filters:{'Usage reports':['csv','json','ndjson']}}); if(!picks?.[0])return; try{await store.add(await parseReport(picks[0])); vscode.window.showInformationMessage('Copilot Pulse imported usage report.');refreshUI();}catch(e){vscode.window.showErrorMessage(`Copilot Pulse import failed: ${e instanceof Error?e.message:String(e)}`);}});
 command('copilotPulse.startSession',async()=>{if(store.session())return vscode.window.showWarningMessage('A Copilot Pulse session is already active.'); const name=await vscode.window.showInputBox({prompt:'Focus session purpose',value:'Focused Copilot work'}); if(name===undefined)return; const target=Number(await vscode.window.showInputBox({prompt:'Credit target',value:'25'}) ?? 25); const mins=Number(await vscode.window.showInputBox({prompt:'Duration in minutes (optional)',value:'45'}) ?? 45); const [a]=period('daily'); await store.saveSession({id:`session-${Date.now()}`,name,startedAt:new Date().toISOString(),endsAt:mins?new Date(Date.now()+mins*60000).toISOString():undefined,target,warningAt:target*.8,startCredits:used(store.samples(),a,new Date()),pausedMs:0});refreshUI();});
 command('copilotPulse.endSession',async()=>{const s=store.session();if(!s)return; const consumption=sessionConsumed(s,store.samples()); await store.saveSession(undefined); vscode.window.showInformationMessage(`Focus session complete: ${s.name} used ${consumption.toFixed(1)} credits against a ${s.target} target.`);refreshUI();});
 command('copilotPulse.refresh',()=>refreshUI()); command('copilotPulse.enableEconomy',async()=>{await context.globalState.update('economy.until',Date.now()+3600000);vscode.window.showInformationMessage('Economy Mode enabled for one hour. It is advisory and never blocks Copilot.');}); command('copilotPulse.snooze',async()=>{await context.globalState.update('snooze.until',Date.now()+3600000);vscode.window.showInformationMessage('Copilot Pulse alerts snoozed for one hour.');}); command('copilotPulse.configureBudgets',()=>vscode.commands.executeCommand('workbench.action.openSettings','copilotPulse.budgets')); command('copilotPulse.explainAlert',()=>dashboard.open()); command('copilotPulse.exportHistory',async()=>{const uri=await vscode.window.showSaveDialog({defaultUri:vscode.Uri.file('copilot-pulse-history.json')});if(uri)await store.export(uri);}); command('copilotPulse.deleteHistory',async()=>{if(await vscode.window.showWarningMessage('Delete all local Copilot Pulse history?','Delete')==='Delete'){await store.clear();refreshUI();}});
 context.subscriptions.push(vscode.workspace.onDidChangeConfiguration(e=>{if(e.affectsConfiguration('copilotPulse'))refreshUI();}),vscode.window.onDidChangeWindowState(s=>{if(s.focused)refreshUI();})); refreshUI();
}
function alerts(store:Store,budgets:DashboardModel['budgets'],ps:DashboardModel['projections'],ratio:number,current:number,stale:boolean):Alert[]{const out:Alert[]=[]; if(stale)out.push({id:'stale',severity:'ambient',title:'Usage data is stale',explanation:['Forecasting is paused until a new report or snapshot is available.'],fingerprint:'stale',createdAt:new Date().toISOString()}); const d=budgets.find(x=>x.kind==='daily'); if(d && d.amount && d.consumed/d.amount>=.8)out.push({id:'daily',severity:d.consumed>=d.amount?'critical':'warning',title:'Daily target is near',explanation:[`${d.consumed.toFixed(1)} of ${d.amount} credits are consumed.`],fingerprint:'daily',createdAt:new Date().toISOString()}); if(ratio>=2.5&&current>=10)out.push({id:'surge',severity:'warning',title:'Copilot usage surge detected',explanation:[`Current rate is ${ratio.toFixed(1)}× your baseline.`],fingerprint:'surge',createdAt:new Date().toISOString()}); return out;}
function notify(m:DashboardModel,store:Store){const snooze=0; if(m.freshness.stale||snooze>Date.now())return; const a=m.alerts.find(x=>x.severity==='warning'||x.severity==='critical');if(a&&!store.fingerprints().has(a.fingerprint)){store.remember(a.fingerprint);vscode.window.showWarningMessage(a.title,...['View usage','Snooze 1 hour']).then(x=>{if(x==='View usage')vscode.commands.executeCommand('copilotPulse.openDashboard');if(x==='Snooze 1 hour')vscode.commands.executeCommand('copilotPulse.snooze');});}}
export function deactivate() {}
