import * as vscode from 'vscode';
import { Alert, CompletedSession, DashboardModel, DataQuality, FocusSession, ProviderDiagnostics } from './domain';
import { baseline, confidenceRank, forecast, pacing, period, rate, sessionConsumed, spike, state, used } from './analytics';
import { Dashboard } from './dashboard';
import { CopilotQuotaProvider, parseReport, PersonalUsageProvider, ProviderRegistry } from './providers';
import { Store } from './storage';

type Command = () => unknown | Promise<unknown>;
export function activate(context: vscode.ExtensionContext) {
  const store = new Store(context); const config = () => vscode.workspace.getConfiguration('copilotPulse');
  const output=vscode.window.createOutputChannel('Copilot Pulse'); const log=(message:string)=>output.appendLine(`[${new Date().toLocaleTimeString()}] ${message}`);
  let dashboard: Dashboard; let status: vscode.StatusBarItem;
  const getModel = (): DashboardModel => {
    const samples = store.samples().sort((a,b)=>a.observedAt.localeCompare(b.observedAt)); const now=new Date(); const quality:DataQuality=samples.at(-1)?.quality ?? 'estimated';
    const budgets=(['daily','weekly','billingCycle'] as const).map(kind=>{const [periodStart,periodEnd]=period(kind,now);return {kind,amount:config().get<number>(`budgets.${kind}`,0),consumed:used(samples,periodStart,now),periodStart,periodEnd};});
    const current=rate(samples,now,config().get('spike.windowMinutes',30)); const base=baseline(samples,now); const ratio=current/Math.max(base,2); const projections=budgets.map(b=>forecast(b,current,quality,samples));
    const last=samples.at(-1)?.observedAt; const staleHours=quality==='exact'?1:quality==='delayed'?36:quality==='imported'?48:24; const stale=!last||Date.now()-new Date(last).getTime()>staleHours*3600000;
    const active=store.session(); const pace={daily:pacing(budgets[0],now),weekly:pacing(budgets[1],now)}; const risky=projections.some(p=>p.projectedUsage>p.budget.amount);
    const provider=store.diagnostics() ?? {id:'manual',quality,lastRefresh:last,detail:'Manual snapshots and imported reports are local only.'};
    const quota=store.quota(); const quotaStale=!!quota&&Date.now()-new Date(quota.observedAt).getTime()>15*60*1000;
    return {quality:freshnessQuality(quota,quality),freshness:{observedAt:quota?.observedAt??last,stale:quota?quotaStale:stale,explanation:quotaStale?'Copilot quota snapshot is stale; refresh to update it.':quota?'Live Copilot quota snapshot.':'Usage data is stale; exact-minute alerts and forecasts are paused.'},now:now.toISOString(),budgets,ratePerHour:current,baselineRate:base,ratio,weather:stale?'Unknown':state(ratio,current*(config().get('spike.windowMinutes',30)/60),risky),projections,trail:samples,session:active,sessions:store.completedSessions(),alerts:buildAlerts(budgets,projections,ratio,current,stale,pace,quality,samples,config()),pacing:pace,officialAllowance:positive(config().get('budgets.officialAllowance',0)),officialBudget:positive(config().get('budgets.officialBudget',0)),quota,provider,economyUntil:store.economyUntil()};
  };
  const refresh = () => { const m=getModel(); if(!config().get('enabled',true)){status.hide();return;} const daily=m.projections.find(p=>p.budget.kind==='daily'); const mode=config().get<string>('statusBar.mode','adaptive'); const runway=daily?.exhaustionAt?`${Math.max(0,Math.round((daily.exhaustionAt.getTime()-Date.now())/3600000))}h runway`:''; status.text=m.freshness.stale?'$(circle-slash) Copilot · Data stale':mode==='budget'?`$(pulse) Copilot · ${daily?.budget.consumed.toFixed(0)} / ${daily?.budget.amount}`:mode==='burnRate'?`$(pulse) Copilot · ${m.weather} ${m.ratio.toFixed(1)}×`:m.weather==='Critical'?`$(flame) Copilot · ${runway}`:`$(pulse) Copilot · ${m.weather}${runway?` · ${runway}`:''}`; status.tooltip=`Copilot Pulse — ${m.quality}; ${m.freshness.explanation}`; status.show(); dashboard?.render(); void notify(m,store,config); };
  dashboard=new Dashboard(context.extensionUri,getModel,message=>{const c=(message as {command?:string})?.command; const commands:Record<string,string>={refresh:'copilotPulse.refresh',snapshot:'copilotPulse.enterSnapshot',import:'copilotPulse.importReport',startSession:'copilotPulse.startSession',endSession:'copilotPulse.endSession',pauseSession:'copilotPulse.pauseSession',extendSession:'copilotPulse.extendSession',economy:'copilotPulse.enableEconomy',snooze:'copilotPulse.snooze',settings:'copilotPulse.configureBudgets',export:'copilotPulse.exportHistory'};if(c&&commands[c])void vscode.commands.executeCommand(commands[c]);});
  status=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right,100); status.command='copilotPulse.openDashboard'; context.subscriptions.push(status);
  const command=(id:string,fn:Command)=>context.subscriptions.push(vscode.commands.registerCommand(id,fn));
  context.subscriptions.push(output);
  command('copilotPulse.getPersonalToken',()=>context.secrets.get('copilotPulse.personalUsageToken'));
  command('copilotPulse.openDashboard',()=>dashboard.open());
  command('copilotPulse.enterSnapshot',()=>enterSnapshot(store,refresh));
  command('copilotPulse.importReport',()=>importReport(store,refresh));
  command('copilotPulse.refresh',()=>refreshProvider(store,config,refresh,false,log));
  command('copilotPulse.showLogs',()=>output.show(true));
  command('copilotPulse.connectPersonalApi',()=>connectPersonalApi(context,refresh));
  command('copilotPulse.startSession',()=>startSession(store,refresh));
  command('copilotPulse.pauseSession',()=>pauseSession(store,refresh));
  command('copilotPulse.extendSession',()=>extendSession(store,refresh));
  command('copilotPulse.endSession',()=>endSession(store,refresh));
  command('copilotPulse.enableEconomy',()=>economy(store,refresh));
  command('copilotPulse.snooze',async()=>{await store.setSnoozeUntil(Date.now()+3600000);vscode.window.showInformationMessage('Copilot Pulse alerts snoozed for one hour.');});
  command('copilotPulse.configureBudgets',()=>vscode.commands.executeCommand('workbench.action.openSettings','copilotPulse'));
  command('copilotPulse.explainAlert',()=>dashboard.open());
  command('copilotPulse.exportHistory',async()=>{const uri=await vscode.window.showSaveDialog({defaultUri:vscode.Uri.file('copilot-pulse-history.json')});if(uri)await store.export(uri);});
  command('copilotPulse.deleteHistory',async()=>{if(await vscode.window.showWarningMessage('Delete all local Copilot Pulse history and session summaries?','Delete')==='Delete'){await store.clear();refresh();}});
  context.subscriptions.push(vscode.workspace.onDidChangeConfiguration(e=>{if(e.affectsConfiguration('copilotPulse'))refresh();}),vscode.window.onDidChangeWindowState(s=>{if(s.focused)refresh();})); refresh(); void refreshProvider(store,config,refresh,true,log);
}
async function enterSnapshot(store:Store, refresh:()=>void){const consumed=await numberInput('Current credits consumed this billing cycle');if(consumed===undefined)return;const allowance=await numberInput('Official allowance (optional)',true);const previous=store.samples().filter(s=>s.sourceId==='manual').at(-1);await store.add([{id:`manual-${Date.now()}`,observedAt:new Date().toISOString(),credits:Math.max(0,consumed-(previous?.cumulativeCredits??0)),cumulativeCredits:consumed,quality:'estimated',sourceId:'manual',note:allowance===undefined?undefined:`Official allowance: ${allowance}`}]);await store.saveDiagnostics({id:'manual',quality:'estimated',lastRefresh:new Date().toISOString(),detail:'Manual snapshot; values between snapshots are estimated.'});refresh();}
async function importReport(store:Store,refresh:()=>void){const file=(await vscode.window.showOpenDialog({canSelectMany:false,filters:{'Usage reports':['csv','json','ndjson']}}))?.[0];if(!file)return;try{const rows=await parseReport(file);await store.add(rows);await store.saveDiagnostics({id:'import',quality:'imported',lastRefresh:new Date().toISOString(),detail:`Imported ${rows.length} usage samples locally.`});vscode.window.showInformationMessage(`Imported ${rows.length} Copilot Pulse samples.`);refresh();}catch(e){vscode.window.showErrorMessage(`Import failed: ${e instanceof Error?e.message:String(e)}`);}}
async function refreshProvider(store:Store,cfg:()=>vscode.WorkspaceConfiguration,refresh:()=>void,silent=false,log:(message:string)=>void=()=>{}){const kind=cfg().get<string>('dataSource','auto');log(`Refresh requested. Selected source: ${kind}.`);if(kind==='manual'||kind==='import'){if(!silent)vscode.window.showInformationMessage('No remote source is selected. Choose Copilot Quota, import a report, or enter a snapshot.');return;}const token=kind==='personal-api'?await vscode.commands.executeCommand<string>('copilotPulse.getPersonalToken'):undefined;const registry=new ProviderRegistry(cfg().get('providers.organization',''),cfg().get('providers.enterprise',''));const provider=(kind==='auto'||kind==='copilot-quota'||kind==='personal-api')?new CopilotQuotaProvider(log,!silent):registry.select(kind);if(!provider){log(`No provider is configured for ${kind}.`);if(!silent)vscode.window.showErrorMessage(`Configure the required organization or enterprise before using ${kind}.`);return;}try{const allowance=await provider.getAllowance();if(allowance)await store.saveQuota(allowance);const rows=await provider.getUsage();await store.add(rows);const freshness=await provider.getFreshness();await store.saveDiagnostics({id:provider.id,quality:provider.quality,lastRefresh:new Date().toISOString(),detail:freshness.explanation});log(`Refresh succeeded with provider ${provider.id}.`);if(!silent)vscode.window.showInformationMessage(allowance?`Copilot quota refreshed: ${allowance.unlimited?'Unlimited':`${allowance.consumed ?? 0} / ${allowance.amount} credits`}.`:`Copilot Pulse refreshed ${rows.length} ${provider.quality} samples.`);refresh();}catch(e){log(`Refresh failed: ${e instanceof Error?e.message:String(e)}`);if(provider.id==='copilot-quota'&&token){const billing=new PersonalUsageProvider(token);try{const rows=await billing.getUsage();await store.add(rows);const freshness=await billing.getFreshness();await store.saveDiagnostics({id:billing.id,quality:billing.quality,lastRefresh:new Date().toISOString(),detail:freshness.explanation});log('Billing fallback succeeded; native quota remains unavailable.');if(!silent)vscode.window.showWarningMessage('Native quota unavailable; showing direct billing data only.');refresh();return;}finally{billing.dispose();}}await store.saveDiagnostics({id:provider.id,quality:provider.quality,lastError:new Date().toISOString(),detail:e instanceof Error?e.message:String(e)});if(!silent)vscode.window.showErrorMessage(`Copilot Pulse refresh failed: ${e instanceof Error?e.message:String(e)}`);refresh();}finally{provider.dispose();}}
async function connectPersonalApi(context:vscode.ExtensionContext,refresh:()=>void){const raw=await vscode.window.showInputBox({prompt:'GitHub fine-grained PAT (User permissions → Plan: Read). Do not enter VSCE_PAT.',password:true,ignoreFocusOut:true,validateInput:v=>{const token=v.trim();return !token?'A GitHub token is required.':token.startsWith('github_pat_')?undefined:'Use a GitHub fine-grained PAT (normally starts github_pat_), not an Azure DevOps VSCE_PAT.';}});if(!raw)return;const token=raw.trim();await context.secrets.store('copilotPulse.personalUsageToken',token);await vscode.workspace.getConfiguration('copilotPulse').update('dataSource','personal-api',vscode.ConfigurationTarget.Global);vscode.window.showInformationMessage('Personal Usage API connected. Refreshing usage now.');refresh();await vscode.commands.executeCommand('copilotPulse.refresh');}
async function startSession(store:Store,refresh:()=>void){if(store.session())return vscode.window.showWarningMessage('A focus session is already active.');const name=await vscode.window.showInputBox({prompt:'Focus session purpose',value:'Focused Copilot work'});if(!name)return;const target=await numberInput('Credit target');if(target===undefined)return;const minutes=await numberInput('Duration in minutes (optional)',true);const note=await vscode.window.showInputBox({prompt:'Optional note'});await store.saveSession({id:`session-${Date.now()}`,name,startedAt:new Date().toISOString(),endsAt:minutes?new Date(Date.now()+minutes*60000).toISOString():undefined,target,warningAt:target*.8,startCredits:0,pausedMs:0,note});refresh();}
async function pauseSession(store:Store,refresh:()=>void){const s=store.session();if(!s)return; if(s.pausedAt){s.pausedMs+=Date.now()-new Date(s.pausedAt).getTime();delete s.pausedAt;vscode.window.showInformationMessage('Focus session resumed.');}else{s.pausedAt=new Date().toISOString();vscode.window.showInformationMessage('Focus session paused.');}await store.saveSession(s);refresh();}
async function extendSession(store:Store,refresh:()=>void){const s=store.session();if(!s)return;const mins=await numberInput('Minutes to add');if(!mins)return;s.endsAt=new Date((s.endsAt?new Date(s.endsAt):new Date()).getTime()+mins*60000).toISOString();await store.saveSession(s);refresh();}
async function endSession(store:Store,refresh:()=>void){const s=store.session();if(!s)return;const samples=store.samples().filter(x=>new Date(x.observedAt)>=new Date(s.startedAt));const consumed=sessionConsumed(s,store.samples());const peak=samples.sort((a,b)=>b.credits-a.credits)[0];const complete:CompletedSession={...s,endedAt:new Date().toISOString(),endCredits:consumed,consumed,largestSurge:peak?{observedAt:peak.observedAt,credits:peak.credits}:undefined};await store.completeSession(complete);vscode.window.showInformationMessage(`${s.name}: ${consumed.toFixed(1)} credits against ${s.target}.`);refresh();}
async function economy(store:Store,refresh:()=>void){const selected=await vscode.window.showQuickPick([{label:'Enable for 1 hour',value:1},{label:'Enable until end of day',value:0}]);if(!selected)return;const until=selected.value?new Date(Date.now()+3600000):new Date(new Date().setHours(23,59,59,999));await store.setEconomyUntil(until.toISOString());vscode.window.showInformationMessage(`Economy Mode enabled until ${until.toLocaleTimeString()}. It is advisory only.`);refresh();}
function buildAlerts(budgets:DashboardModel['budgets'],projections:DashboardModel['projections'],ratio:number,current:number,stale:boolean,pace:DashboardModel['pacing'],quality:DataQuality,samples:DashboardModel['trail'],cfg:vscode.WorkspaceConfiguration):Alert[]{const now=new Date().toISOString(),out:Alert[]=[];if(stale)return [{id:'stale',severity:'ambient',title:'Usage data is stale',explanation:['Refresh, import, or enter a new snapshot. Minute-level spike alerts are paused.'],fingerprint:'stale',createdAt:now}];for(const b of budgets){if(!b.amount)continue;const pct=b.consumed/b.amount*100;const critical=cfg.get<number>('thresholds.critical',100),warn=cfg.get<number>('thresholds.warning',80),info=cfg.get<number>('thresholds.informational',60);if(pct>=info)out.push({id:`threshold-${b.kind}`,budgetKind:b.kind,severity:pct>=critical?'critical':pct>=warn?'warning':'info',title:`${b.kind} target ${pct>=critical?'reached':'is nearing'}`,explanation:[`${b.consumed.toFixed(1)} of ${b.amount} credits (${pct.toFixed(0)}%).`],fingerprint:`threshold-${b.kind}-${pct>=critical?'critical':pct>=warn?'warning':'info'}`,createdAt:now});}if(pace.daily>=.15)out.push({id:'pacing',severity:'warning',title:'You are running ahead of today’s plan',explanation:[`Daily pacing is ${(pace.daily*100).toFixed(0)} percentage points ahead.`],fingerprint:'pacing',createdAt:now});const detected=spike(samples,new Date(),cfg.get('spike.windowMinutes',30),cfg.get('spike.multiplier',2.5),cfg.get('spike.minimumCredits',10),cfg.get('spike.minimumSamples',8));if(quality==='exact'&&detected.triggered)out.push({id:'surge',severity:'warning',title:'Copilot usage surge detected',explanation:[`${detected.current.toFixed(1)} credits/hour is ${detected.ratio.toFixed(1)}× your baseline.`],fingerprint:'surge',createdAt:now});for(const p of projections){if(p.projectedUsage>p.budget.amount*cfg.get('forecast.warningPercentage',110)/100&&confidenceRank(p.confidence)>=confidenceRank(cfg.get('forecast.minimumConfidence','medium'))){out.push({id:`forecast-${p.budget.kind}`,severity:'warning',budgetKind:p.budget.kind,title:`${p.budget.kind} target likely to be exceeded`,explanation:[`Projected ${p.projectedUsage.toFixed(0)} credits against ${p.budget.amount}; ${p.confidence} confidence.`],fingerprint:`forecast-${p.budget.kind}`,createdAt:now});}}return out;}
async function notify(m:DashboardModel,store:Store,cfg:()=>vscode.WorkspaceConfiguration){if(m.freshness.stale||store.snoozeUntil()>Date.now()||cfg().get<string>('notifications.level','actionable')==='ambient')return;const alert=m.alerts.find(x=>x.severity==='warning'||x.severity==='critical');if(!alert)return;const previous=store.alertState(alert.fingerprint);const cooldown=cfg().get('spike.cooldownMinutes',60)*60000;if(previous?.lastNotifiedAt&&Date.now()-new Date(previous.lastNotifiedAt).getTime()<cooldown)return;await store.saveAlertState({fingerprint:alert.fingerprint,lastNotifiedAt:new Date().toISOString()});const choice=await vscode.window.showWarningMessage(alert.title,'View usage','Snooze 1 hour');if(choice==='View usage')await vscode.commands.executeCommand('copilotPulse.openDashboard');if(choice==='Snooze 1 hour')await store.setSnoozeUntil(Date.now()+3600000);}
async function numberInput(prompt:string,optional=false){const value=await vscode.window.showInputBox({prompt,validateInput:v=>!v&&optional?undefined:Number.isFinite(Number(v))&&Number(v)>=0?undefined:'Enter a non-negative number'});return value===undefined||(!value&&optional)?undefined:Number(value);}
function positive(v:number){return v>0?v:undefined;}
function freshnessQuality(quota:DashboardModel['quota'],fallback:DataQuality):DataQuality{return quota?.quality??fallback;}
export function deactivate() {}
